version: "3"

services:
  web:
    build: .
    volumes:
      - ./src:/src
    command: python /src/manage.py runserver 0.0.0.0:8080
    ports:
      - 9050:8080
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    command: -p ${DB_PORT}
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
